name: ci
on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    # Daily, at a semi-randomly chosen time.
    - cron: "37 3 * * *"

permissions:
  contents: read

jobs:
  test:
    runs-on: "ubuntu-slim"
    strategy:
      matrix:
        rust:
          - { version: "1.85",   unstable: true }
          - { version: "stable", unstable: true }
          - { version: "beta",   unstable: true }
          - { version: "nightly" }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust.version }}
          components: clippy, rustfmt

      - name: Check Format
        if: ${{ matrix.rust.version == 'stable' }}
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Documentation
        run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: -D warnings

      - name: Tests
        run: cargo test
        env:
          RUSTC_BOOTSTRAP: ${{ matrix.rust.unstable && '1' || '' }}
          RUSTFLAGS: ${{ matrix.rust.unstable && '--cfg=outlined_unstable' || '' }}
          RUSTDOCFLAGS: ${{ matrix.rust.unstable && '--cfg=outlined_unstable' || '' }}
